In [2]:
import numpy as np
## Define Numpy Array
a = np.array(1) # number
print(type(a))
a = np.array([1,2,3]) #list
print(type(a))
a = np.array((1,2,3)) #tuple
print(type(a))
b = np.array(a) #array
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# a.ndim  # Number of Dimention
# a.size  # Total elements counts
# a.shape   # Total Values 

In [59]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

In [23]:
np.arange(2,21,2)  # Create array start with 2 end with 21 step by 3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
np.zeros((4,6))  # First 4 is Column Vertical axis 0 -- Second is Row Horizental axis 1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((4,6), dtype=np.int64)  # Default is Float  .. create with int

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [31]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
np.empty(6)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313, 1.69759663e-313,
       2.12199579e-313, 2.54639495e-313])

In [39]:
np.linspace(1,2,33) # array start with 1 and end with 2 last argument number of steps

array([1.     , 1.03125, 1.0625 , 1.09375, 1.125  , 1.15625, 1.1875 ,
       1.21875, 1.25   , 1.28125, 1.3125 , 1.34375, 1.375  , 1.40625,
       1.4375 , 1.46875, 1.5    , 1.53125, 1.5625 , 1.59375, 1.625  ,
       1.65625, 1.6875 , 1.71875, 1.75   , 1.78125, 1.8125 , 1.84375,
       1.875  , 1.90625, 1.9375 , 1.96875, 2.     ])

In [75]:
a[0:,0:] 

array([[ 1,  2,  8,  4],
       [ 5,  6, 12,  8],
       [ 9, 10, 11, 12]])

In [67]:
a

array([[ 1,  2,  8,  4],
       [ 5,  6, 12,  8],
       [ 9, 10, 11, 12]])

In [78]:
x = np.array([3, 1, 2])
np.sort(x) # Sort the array with values
np.args(x) # Sort the array with Indexx

array([1, 2, 0], dtype=int64)

In [79]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
np.lexsort((b,a)) # Sort by a, then by b

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [84]:
data = np.arange(1,11)
print(data)
print(data[3:])# --> left to right Slicing
print(data[-5:])# --> left to right Slicing

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[ 6  7  8  9 10]


In [62]:
np.arange(1,11).reshape((2,5)) # (5,2) (10,1), (1,10)  with reshape option

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [91]:
a = np.random.randint(0,255, size=(5,5)) # Create random array int datatype with size
a

array([[209,  65,  92, 156, 192],
       [ 69, 165, 166,  51,   8],
       [141,  82,  81,  56, 120],
       [ 75, 251, 213, 150,  23],
       [217, 189,  16,  54,  59]])

In [92]:
a[a<=50] # Broad Castig array 

array([ 8, 23, 16])

In [93]:
a[(a % 3) == 0]

array([156, 192,  69, 165,  51, 141,  81, 120,  75, 213, 150, 189,  54])

In [99]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.array([9, 10])
np.concatenate((a, b, c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[5, 6],
              [7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [110]:
# np.concatenate((x,y), axis=0) # Joining with Vertical
# np.vstack((x, y))             # Joining with Vertical
# np.vsplit(np.vstack((x, y)), 2) # Spliting with Vertial and given the dimension 

# np.concatenate((x,y), axis=1) # Joining with Horizental
# np.hstack((x, y))             # Joining with Horizental
# np.hsplit(np.hstack((x, y)), 2) # Spliting with Horizental and given the dimension 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [117]:
a = np.arange(1,101).reshape((10,10))
print(a)
print(a[5:,5:]) # Slicing 
a[5:,5:] += 20  # Change the value with Slicing
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 56  57  58  59  60]
 [ 66  67  68  69  70]
 [ 76  77  78  79  80]
 [ 86  87  88  89  90]
 [ 96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  76  77  78  79  80]
 [ 61  62  63  64  65  86  87  88  89  90]
 [ 71  72  73  74  75  96  97  98  99 100]
 [ 81  82  83  84  85 106 107 108 109 110]
 [ 91  92  93  94  95 116 117 118 119 120]]


In [119]:
a = [1,2,3,4,6]
[i+5 for i in a]  # List adding process
a = np.array([1,2,3,4,6])
a + 5

array([ 6,  7,  8,  9, 11])

In [160]:
a = np.arange(1,101).reshape((10,10))
print(a)
print("Sum of the array is {}".format(a.sum()))
print("Sum of the array with Vertically is {}".format(a.sum(axis=0)))
print("Sum of the array with Horizentally is {}".format(a.sum(axis=1)))
print("Min of the array is {}".format(a.min()))
print("Min of the array with Vertically is {}".format(a.min(axis=0)))
print("Min of the array with Horizentally is {}".format(a.min(axis=1)))
print("Max of the array is {}".format(a.max()))
print("Max of the array with Vertically is {}".format(a.max(axis=0)))
print("Max of the array with Horizentally is {}".format(a.max(axis=1)))
print("Mean of the array is {}".format(a.mean()))
print("Mean of the array with Vertically is {}".format(a.mean(axis=0)))
print("Mean of the array with Horizentally is {}".format(a.mean(axis=1)))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
Sum of the array is 5050
Sum of the array with Vertically is [460 470 480 490 500 510 520 530 540 550]
Sum of the array with Horizentally is [ 55 155 255 355 455 555 655 755 855 955]
Min of the array is 1
Min of the array with Vertically is [ 1  2  3  4  5  6  7  8  9 10]
Min of the array with Horizentally is [ 1 11 21 31 41 51 61 71 81 91]
Max of the array is 100
Max of the array with Vertically is [ 91  92  93  94  95  96  97  98  99 100]
Max of the array with Horizentally is [ 10  20  30  40  50  60  70  80  90 100]
Mean of the array is 50.5
Mean of the array 

In [161]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [166]:
print(a.sum(axis=0)) # Sum of 3 dimention with vertical   1 + 10 + 19   2 + 11 + 20   3 + 12 + 21
print()
print(a.sum(axis=1)) # Sum of 3 dimention with Horizental 1 + 4 + 7    2 + 5 + 8      3 + 6 + 9
print()
print(a.sum(axis=2)) # Sum of All dimension               1 + 2 + 3    4 + 5 + 6      7 + 8 + 9
print()
print(a.mean(axis=2))

[[30 33 36]
 [39 42 45]
 [48 51 54]]

[[12 15 18]
 [39 42 45]
 [66 69 72]]

[[ 6 15 24]
 [33 42 51]
 [60 69 78]]

[[ 2.  5.  8.]
 [11. 14. 17.]
 [20. 23. 26.]]
