In [1]:
import numpy as np

In [2]:
np.sum([1,3])

4

In [3]:
sum([1,3])

4

In [4]:
def abc():
    print("hello")
    
def abc():
    print("Pakistan")
    
abc()    

Pakistan


In [5]:
np.__version__

'1.21.5'

In [6]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in /home/muhammadqasim/anaconda3/lib/python3.7/site-packages (1.18.2)


In [6]:
%history

import numpy as np
np.sum([1,3])
sum([1,3])
def abc():
    print("hello")
    
def abc():
    print("Pakistan")
    
abc()
np.__version__
%history


In [7]:
%time list(range(2000000))[:20]

CPU times: total: 78.1 ms
Wall time: 64.8 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [10]:
%time np.arange(2000000)

CPU times: user 6.29 ms, sys: 1.17 ms, total: 7.46 ms
Wall time: 12.7 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [8]:
%time [x+5 for x in range(1,1000000)][:20]

CPU times: total: 78.1 ms
Wall time: 83.8 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [26]:
l = list(range(1,1000000))
l2 = list(enumerate(l))
for i, v in l2:
    l[i] = l[i]+5
l[:20] 
%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs


In [9]:
# Two Dimension list adding value 5 

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Before Adding 5")
print(a)
print()
for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c] + 5
        
print("After Adding 5")        
print(a) 

Before Adding 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After Adding 5
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [48]:
a = np.arange(1,10).reshape((3,3))
a = a+5
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
a = np.arange(1,28).reshape((3,3,3))
a = a+5
a

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [61]:
a = np.arange(1,28).reshape((3,3,3))
a = a%2
a

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]])

In [10]:
a = np.random.randn(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a = a * 10
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[ 3.52161778e+00,  1.90597199e+00, -9.26278350e+00,
             4.82568612e+00,  1.46012824e+01],
           [-5.61413036e+00,  3.21868023e+00,  9.39061468e+00,
             5.82073557e+00,  7.57423465e+00],
           [ 5.80532336e+00, -4.88539389e+00, -1.98951203e+01,
             1.20496400e+00,  4.57436357e+00],
           [-1.02022317e+01, -1.30694767e+01, -6.33036582e+00,
             2.58552938e-01,  6.86842007e+00],
           [ 5.20931569e+00,  1.21096903e+01, -1.87696394e+00,
            -9.28488245e+00, -1.36615641e+00]],

          [[ 7.93914625e+00, -1.22231410e+01, -7.55916622e+00,
            -1.59603473e+01,  1.06317004e+01],
           [-9.39303982e+00,  2.05481690e+01, -8.43195595e+00,
            -2.64923402e+00, -1.56413270e+01],
           [ 1.08341664e+01, -2.16335432e+00,  1.24304820e+00,
             4.71235298e+00,  1.39965162e+01],
           [ 8.12306190e+00, -6.18551158e+00,  1.07667312e+00,
            -5.04405999e+00, -3.98946099e+00],
        

In [75]:
a = np.arange(1,13).reshape((6,2))
print(a)

print(a * a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[  1   4]
 [  9  16]
 [ 25  36]
 [ 49  64]
 [ 81 100]
 [121 144]]


# a[i,j,k]

In [55]:
#a[2]
#a[2,0]
a[2,0,1]

25

<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [27]:
l = np.arange(1,1000000)
l = l + 5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [28]:
type(l)

numpy.ndarray

In [29]:
l.shape

(999999,)

In [31]:
l.ndim

1

# Dimensions

In [11]:
a = np.array([1])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1]
1
(1,)
int32


In [34]:
a = np.array([1,2,4,5])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 4 5]
1
(4,)
int64


In [36]:
a = np.array([[1,2,4],
              [3,5,6],
              [2,1,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[1 2 4]
 [3 5 6]
 [2 1 5]]
2
(3, 3)
int64


# Creating ndarrays

In [78]:
a = [1,2,3]
print(type(a))

a = np.array(a)
type(a)


<class 'list'>


numpy.ndarray

In [79]:
a = (1,2,3)

print(type(a))

a = np.array(a)
type(a)

<class 'tuple'>


numpy.ndarray

In [80]:
a = {1,2,3}
print(type(a))

a = np.array(a)
type(a)

<class 'set'>


numpy.ndarray

# np.array

In [83]:
l = [1,2,3]
a = np.array(l)
b = np.array(a)
a is b

False

### np.asarray

In [84]:
l = [1,2,3]
a = np.asarray(l)
b = np.asarray(a)
a is b

True