In [9]:
a = [1,2,3,4]

for i in range(len(a)):
    a[i]+= 10

In [10]:
a

[11, 12, 13, 14]

In [11]:
import numpy as np

In [30]:
a = [1,2,3,4]

arr = np.array(a)
type(arr)
arr.ndim

1

In [16]:
arr 

array([1, 2, 3, 4])

In [17]:
arr += 10

In [18]:
arr

array([11, 12, 13, 14])

In [21]:
taxi = np.genfromtxt("nyc_taxis.csv",delimiter = ",", skip_header= True)

In [23]:
taxi[0:2]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        1.165e+01, 6.999e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00]])

In [24]:
len(taxi)

89560

In [25]:
type(taxi)

numpy.ndarray

In [26]:
taxi.ndim

2

In [27]:
taxi.shape

(89560, 15)

In [28]:
taxi.shape[0]

89560

In [29]:
taxi.shape[1]

15

# 3 attributes of numpy
* ndim
* shape
* dtype

In [33]:
taxi[1][5]

2.0

In [34]:
taxi[1,5]

2.0

In [39]:
taxi[:3,3:8]

array([[ 5.  ,  0.  ,  2.  ,  4.  , 21.  ],
       [ 5.  ,  0.  ,  2.  ,  1.  , 16.29],
       [ 5.  ,  0.  ,  2.  ,  6.  , 12.7 ]])

In [40]:
taxi[2,3] = 6

In [41]:
taxi[:3,3:8]

array([[ 5.  ,  0.  ,  2.  ,  4.  , 21.  ],
       [ 5.  ,  0.  ,  2.  ,  1.  , 16.29],
       [ 6.  ,  0.  ,  2.  ,  6.  , 12.7 ]])

In [45]:
fare = taxi[:,9]
fee = taxi[:,10]

In [46]:
total = fare + fee
total

array([52.8, 46.3, 37.8, ..., 52.8, 35.8, 49.3])

In [47]:
total = taxi[:,9] + taxi[:,10]


In [50]:
total_amt = taxi[:5,9:13].sum(axis = 1)
total_amt

array([69.99, 54.3 , 37.8 , 32.76, 18.8 ])

In [ ]:
feb_rides = 13333

In [51]:
feb_rides = sum(taxi[:,1]==2)
feb_rides

13333

In [55]:
bol = taxi[:,1]==2
bol

array([False, False, False, ..., False, False, False])

In [57]:
taxi[bol,].shape[0]

13333

In [54]:
taxi[bol,1]

array([2., 2., 2., ..., 2., 2., 2.])

In [81]:
a = np.zeros((taxi.shape[0],1))

In [82]:
a

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [84]:
taxi = np.concatenate([taxi,a], axis = 1)

In [89]:
taxi[:,15]

array([0., 0., 0., ..., 0., 0., 0.])

In [90]:
taxi[taxi[:,5] == 1,15] = 5
taxi[taxi[:,5] == 3,15] = 5
taxi[taxi[:,5] == 5,15] = 5

array([2., 2., 2., ..., 2., 2., 2.])

In [91]:
loc = taxi[:,5]

taxi[(loc == 1) |(loc == 3) |(loc == 5),15] = 5

In [ ]:
&