In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
A = np.random.randn(10)

In [10]:
A

array([ 0.50626083, -0.90438673, -1.46887491,  0.03217181,  0.20829086,
       -1.18016839, -1.84950835, -0.754105  , -1.11635458, -0.63298084])

In [11]:
B = np.random.randn(10)
B

array([ 1.91309778, -1.24350788,  0.19139725, -0.9066442 ,  0.57258474,
       -0.70678953, -0.07473773, -0.66990306, -0.19474239,  0.22022009])

In [12]:
np.add(A,B)

array([ 2.4193586 , -2.14789462, -1.27747766, -0.87447239,  0.78087561,
       -1.88695791, -1.92424608, -1.42400806, -1.31109697, -0.41276075])

In [13]:
np.maximum(A,B)

array([ 1.91309778, -0.90438673,  0.19139725,  0.03217181,  0.57258474,
       -0.70678953, -0.07473773, -0.66990306, -0.19474239,  0.22022009])

In [14]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufunc'
import webbrowser
webbrowser.open(website)

True